# Generated by Django 5.0.3 on 2024-03-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
