# Generated by Django 5.0.3 on 2024-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0002_sign_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cdate', models.CharField(max_length=20)),
                ('cinst', models.CharField(max_length=200)),
            ],
        ),
    ]
