# Generated by Django 5.0.3 on 2024-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0003_client_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_instructions',
            name='clawyer',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
