# Generated by Django 5.0.3 on 2024-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0004_client_instructions_clawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_instructions',
            name='case',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
