# Generated by Django 5.0.3 on 2024-03-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0005_client_instructions_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='lawyer_timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=30)),
                ('tdate', models.CharField(max_length=20)),
                ('ttime', models.CharField(max_length=20)),
                ('tmsg', models.CharField(max_length=200)),
            ],
        ),
    ]
