# Generated by Django 5.0.3 on 2024-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='img',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
