# Generated by Django 5.0.3 on 2024-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_signup_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('lawyer_name', models.CharField(max_length=100)),
            ],
        ),
    ]
