# Generated by Django 5.0.3 on 2024-04-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_upload_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_document',
            name='document_file',
            field=models.FileField(upload_to='image/'),
        ),
    ]
