# Generated by Django 5.0.3 on 2024-04-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_alter_upload_document_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_document',
            name='document_file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
