# Generated by Django 5.0.3 on 2024-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_alter_upload_document_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='lawyer',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
