# Generated by Django 5.0.3 on 2024-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_signup_lawyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('d1', models.CharField(max_length=30)),
                ('d2', models.CharField(max_length=30)),
                ('d3', models.CharField(max_length=30)),
                ('d4', models.CharField(max_length=30)),
                ('d5', models.CharField(max_length=30)),
            ],
        ),
    ]
