# Generated by Django 5.0.3 on 2024-04-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
