# Generated by Django 5.0.3 on 2024-03-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cemail', models.EmailField(max_length=254)),
                ('csub', models.CharField(max_length=200)),
                ('cmsg', models.CharField(max_length=200)),
            ],
        ),
    ]
