# Generated by Django 5.0.3 on 2024-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contactus_csub'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmae', models.CharField(max_length=20)),
                ('acontact', models.CharField(max_length=10)),
                ('aemail', models.EmailField(max_length=254)),
                ('adate', models.CharField(max_length=10)),
                ('atime', models.CharField(max_length=10)),
                ('amsg', models.CharField(max_length=100)),
            ],
        ),
    ]
