# Generated by Django 5.0.3 on 2024-03-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='anmae',
            new_name='aname',
        ),
    ]
