# Generated by Django 5.0.3 on 2024-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_lawyer_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cimg', models.ImageField(upload_to='image/')),
                ('cname', models.CharField(max_length=20)),
                ('cprofession', models.CharField(max_length=20)),
                ('cdesc', models.CharField(max_length=100)),
            ],
        ),
    ]
