# Generated by Django 5.0.3 on 2024-03-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_client_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('ctime', models.CharField(max_length=20)),
            ],
        ),
    ]
