# Generated by Django 5.0.3 on 2024-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_case_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_study',
            name='case_img',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
