# Generated by Django 5.0.3 on 2024-03-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_case_study_case_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_info',
            name='lprofession',
            field=models.CharField(max_length=50),
        ),
    ]
