# Generated by Django 5.0.3 on 2024-03-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_lawyer_info_lprofession'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=2000)),
            ],
        ),
    ]
