# Generated by Django 5.0.3 on 2024-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_case_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_desc',
            name='desc',
            field=models.CharField(max_length=5000),
        ),
    ]
