# Generated by Django 5.0.3 on 2024-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_case_desc_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_desc',
            name='case_challenge',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case_desc',
            name='case_intro',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case_desc',
            name='case_result',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
