# Generated by Django 5.0.3 on 2024-03-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_case_desc_case_challenge_case_desc_case_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_desc',
            name='desc',
        ),
    ]
