# Generated by Django 5.0.3 on 2024-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_case_desc_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_info',
            name='lexp',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
