# Generated by Django 5.0.3 on 2024-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_lawyer_info_lexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_info',
            name='lexperience',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
