# Generated by Django 5.0.3 on 2024-03-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_lawyer_info_lexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_study',
            name='case_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
