# Generated by Django 5.0.3 on 2024-03-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_case_study_case_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimg', models.ImageField(upload_to='image/')),
                ('btitle', models.CharField(max_length=30)),
                ('btype', models.CharField(max_length=30)),
                ('btime', models.CharField(max_length=20)),
                ('bdesc', models.CharField(max_length=5000)),
            ],
        ),
    ]
