# Generated by Django 5.0.3 on 2024-03-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='btitle',
            field=models.CharField(max_length=100),
        ),
    ]
