# Generated by Django 5.0.3 on 2024-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_blog_btitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_info',
            name='lcontact',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer_info',
            name='lcourt',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
