# Generated by Django 5.0.3 on 2024-03-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_lawyer_info_lcontact_lawyer_info_lcourt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_info',
            name='lstate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
