# Generated by Django 5.0.3 on 2024-03-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_lawyer_info_lexpertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer_info',
            name='lexpertise',
        ),
    ]
