# Generated by Django 5.0.3 on 2024-03-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_lawyer_info_lexpertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_info',
            name='lexpertise',
            field=models.CharField(choices=[('Civil Law', 'Civil Law'), ('Family Law', 'Family Law'), ('Cyber Law', 'Cyber Law')], default='Civil Law', max_length=20),
        ),
    ]
