# Generated by Django 5.0.3 on 2024-03-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_lawyer_info_lexpertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_info',
            name='checkbox_field',
            field=models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=20),
        ),
    ]
