# Generated by Django 5.0.3 on 2024-03-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_lawyer_info_checkbox_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer_info',
            name='checkbox_field',
        ),
    ]
