# Generated by Django 5.0.3 on 2024-03-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_lawyer_info_checkbox_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_info',
            name='lexp',
            field=models.CharField(choices=[('FAMILY LAW', 'FAMILY LAW'), ('CIVIL LAW', 'CIVIL LAW'), ('CYBER LAW', 'CYBER LAW')], max_length=100),
        ),
    ]
