# Generated by Django 5.0.3 on 2024-03-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_lawyer_info_lexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_info',
            name='lexp',
            field=models.CharField(max_length=100),
        ),
    ]
