# Generated by Django 5.0.3 on 2024-03-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_lawyer_info_lexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_info',
            name='lexp',
            field=models.CharField(choices=[('Civil Law', 'Civil Law'), ('Family Law', 'Family Law'), ('Business Law', 'Business Law'), ('Education Law', 'Education Law'), ('Criminal Law', 'Criminal Law'), ('Cyber Law', 'Cyber Law')], max_length=20),
        ),
    ]
