# Generated by Django 5.0.3 on 2024-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_lawyer_info_lexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_info',
            name='lexp',
            field=models.CharField(choices=[('OPTION_1', 'Civil Law'), ('OPTION_2', 'Family Law'), ('OPTION_3', 'Business Law'), ('OPTION_4', 'Education Law'), ('OPTION_5', 'Criminal Law'), ('OPTION_6', 'Cyber Law')], default='1', max_length=40),
        ),
    ]
