# Generated by Django 5.0.3 on 2024-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_lawyer_info_lexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_info',
            name='lpassword',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
