# Generated by Django 5.0.3 on 2024-03-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_lawyer_info_lpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_info',
            name='lemail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
