# Generated by Django 5.0.3 on 2024-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_lawyer_info_lemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_info',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
