# Generated by Django 5.0.3 on 2024-03-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_lawyer_info_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer_info',
            name='is_selected',
        ),
    ]
