# Generated by Django 5.0.3 on 2024-03-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_lawyer_info_is_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bimg',
            new_name='bimage',
        ),
    ]
