# Generated by Django 5.0.3 on 2024-03-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_rename_bimage_blog_bimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bimg',
            new_name='bimage',
        ),
    ]
