# Generated by Django 5.0.3 on 2024-03-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_rename_bimg_blog_bimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bimage',
            new_name='bimg',
        ),
    ]
