# Generated by Django 5.0.3 on 2024-03-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_rename_bimage_blog_bimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_info',
            name='lcourt',
            field=models.CharField(choices=[('OPTION_1', 'HIGH COURT'), ('OPTION_2', 'SUPREME COURT'), ('OPTION_3', 'DISTRICT COURT')], default='1', max_length=40),
        ),
    ]
