# Generated by Django 5.0.3 on 2024-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_info',
            name='lcourt',
            field=models.CharField(max_length=40),
        ),
    ]
