# Generated by Django 5.0.3 on 2024-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_lawyer_info_lcourt'),
    ]

    operations = [
        migrations.CreateModel(
            name='court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=40)),
            ],
        ),
    ]
