# Generated by Django 5.0.3 on 2024-04-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_court'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='court',
            new_name='court_name',
        ),
    ]
