# Generated by Django 5.0.3 on 2024-04-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_rename_court_court_court_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='desc',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
