# Generated by Django 5.0.3 on 2024-04-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_court_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('definition', models.CharField(max_length=30)),
                ('law_desc', models.CharField(max_length=2000)),
            ],
        ),
    ]
