# Generated by Django 5.0.3 on 2024-04-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_law'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_info',
            name='lexp',
            field=models.CharField(max_length=50),
        ),
    ]
