# Generated by Django 5.0.3 on 2024-04-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_alter_lawyer_info_lexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='btype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='law',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
