# Generated by Django 5.0.3 on 2024-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_blog_btype_alter_law_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_info',
            name='lstate',
            field=models.CharField(max_length=50),
        ),
    ]
