# Generated by Django 5.0.3 on 2024-04-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_alter_lawyer_info_lstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='definition',
            field=models.CharField(max_length=50),
        ),
    ]
