# Generated by Django 5.0.3 on 2024-03-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aemail', models.EmailField(max_length=254)),
                ('apassword', models.CharField(max_length=20)),
            ],
        ),
    ]
